---
name: test-project
encoding: UTF-8
stdstrings: true
superuser: postgres
extensions:
  - name: citext
    schema: public
  - name: postgres_fdw
    schema: public
  - name: uuid-ossp
    schema: public
foreign_data_wrappers:
  - name: file
    handler: file_fdw_handler
languages:
  - name: plpython3u
    replace: true
